CXXFLAGS=-O2 -Wall -Wextra -Wpedantic -Werror -Wfloat-equal -Wno-unused-parameter -std=c++20
#COMP_FLAGS=-Wall -Wextra -Wpedantic -Werror -Wfloat-equal -Wno-unused-parameter -std=c++20 -fanalyzer

clean:
	find . -type f -perm -555 | grep -v \.sh$$ | xargs rm -f
	rm -f *.o

