#CXX := g++11
#CXX := g++13

CXXFLAGS += -Wall -Wextra -Wpedantic -Werror -Wfloat-equal -Wno-unused-parameter -std=c++20
#COMP_FLAGS += -Wall -Wextra -Wpedantic -Werror -Wfloat-equal -Wno-unused-parameter -std=c++20 -fanalyzer

#LDFLAGS += -lpthread

clean:
	find . -type f -perm -555 | grep -v \.sh$ | xargs rm -f
	rm -f *.o

