#CXXFLAGS += -Wall -Wextra -Wpedantic -Werror -Wno-unused-parameter -std=c++20 -O0 -g3
CXXFLAGS += -Wall -Wextra -Wpedantic -Werror -Wno-unused-parameter -std=c++20 -O3
LDFLAGS += -lfmt

clean:
	find . -type f -executable | xargs rm -f
	rm -f *.o

